name: checkaroo
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  get: ^4.7.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Lexend
      fonts:
        - asset: assets/fonts/lexend/Lexend-Black.ttf
        - asset: assets/fonts/lexend/Lexend-Bold.ttf
        - asset: assets/fonts/lexend/Lexend-ExtraBold.ttf
        - asset: assets/fonts/lexend/Lexend-ExtraLight.ttf
        - asset: assets/fonts/lexend/Lexend-Light.ttf
        - asset: assets/fonts/lexend/Lexend-Regular.ttf
        - asset: assets/fonts/lexend/Lexend-Medium.ttf
        - asset: assets/fonts/lexend/Lexend-SemiBold.ttf
        - asset: assets/fonts/lexend/Lexend-Thin.ttf
  
  
  
